name: Deploy static site to build branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy files to build directory
        run: |
          mkdir -p build
          cp *.html build/
          cp *.css build/
          cp -r assets build/ 2>/dev/null || true

      - name: Deploy to build branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: build
          commit_message: "Build: ${{ github.sha }}"